input_shape :  [64, 64, 3]
encodings_len: 256
margin: 0.4
mode : 'triplet'
distance_type : 'l1'
backbone : 'resnext50'
backbone_weights : 'imagenet'
project_name : 'EmbeddingNet/'
freeze_backbone : False
augmentation_type : 'default'
embeddings_normalization: True

# optimizer parameters
optimizer : 'radam'
learning_rate : 0.001
decay_factor : 0.95
step_size : 2

# embeddings learning training parameters
n_epochs : 1000
n_steps_per_epoch : 200
val_batch_size : 8
val_steps : 200
negatives_selection_mode : 'semihard'
mining_n_classes: 30 # training batch_size = mining_n_classes * mining_n_samples
mining_n_samples: 3

# softmax pretraining parameters
softmax_pretraining : True
softmax_batch_size : 8
softmax_val_steps : 200
softmax_steps_per_epoch : 500
softmax_epochs : 30

#paths
work_dir : 'work_dirs/ai_city_challenge/'
dataset_path : 'D:/Documents/ai_city_challenge/EmbeddingNet/Dataset/'
plot_history : True
encodings_path : 'encodings/'
model_save_name : 'best_model_resnet50_ai_city.h5'
encodings_save_name: 'encodings_resnet50_ai_city.pkl'

# encodings parameters
save_encodings : True
max_num_samples_of_each_class : 30
knn_k : 1