input_shape :  [48, 48, 3]
encodings_len: 256
margin: 0.5
mode : 'triplet'
distance_type : 'l1'
backbone : 'resnet34'
backbone_weights : 'imagenet'
project_name : 'road_signs/'
freeze_backbone : False
augmentation_type : 'default'
embeddings_normalization: True

# optimizer parameters
optimizer : 'radam'
learning_rate : 0.0001
decay_factor : 0.99
step_size : 1

# embeddings learning training parameters
n_epochs : 1000
n_steps_per_epoch : 50
val_batch_size : 8
val_steps : 200
negatives_selection_mode : 'semihard'
mining_n_classes: 5
mining_n_samples: 3

# softmax pretraining parameters
softmax_pretraining : True
softmax_batch_size : 16
softmax_val_steps : 200
softmax_steps_per_epoch : 500
softmax_epochs : 20

#paths
work_dir : 'work_dirs/plates/'
dataset_path : '/home/rauf/datasets/road_signs/road_signs_separated/'
plot_history : True
encodings_path : 'encodings/'
model_save_name : 'best_model_resnet18.h5'
encodings_save_name: 'encodings_resnet18.pkl'

# encodings parameters
save_encodings : True
max_num_samples_of_each_class : 30
knn_k : 1